[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = "1.1.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.12.0"

[[constraint]]
  name = "github.com/infobloxopen/atlas-app-toolkit"
  version = "0.19.0"

[[constraint]]
  name = "github.com/infobloxopen/protoc-gen-gorm"
  version = "0.18.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.11"

[[constraint]]
  name = "github.com/lyft/protoc-gen-validate"
  version = "0.0.5"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.5"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "google.golang.org/genproto"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.24.0"

[[constraints]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraints]]
    name = "github.com/kutty-kumar/commons"
    version = "*"

[prune]
  go-tests = true
  unused-packages = true
