// Code generated by protoc-gen-go. DO NOT EDIT.
// source: catalog/pkg/pb/service.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	_ "github.com/lyft/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TODO: Structure your own protobuf messages. Each protocol buffer message is a
// small logical record of information, containing a series of name-value pairs.
type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_481cb6c23ddb1e62, []int{0}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "service.VersionResponse")
}

func init() { proto.RegisterFile("catalog/pkg/pb/service.proto", fileDescriptor_481cb6c23ddb1e62) }

var fileDescriptor_481cb6c23ddb1e62 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x55, 0x06, 0x0a, 0x5e, 0x80, 0x20, 0xa1, 0x28, 0x74, 0x40, 0x9d, 0x90, 0xa0, 0x3e,
	0x09, 0x36, 0xba, 0x81, 0x10, 0x2b, 0xea, 0xc0, 0x00, 0x93, 0x1d, 0x2e, 0xc6, 0x22, 0xf1, 0x59,
	0xb6, 0x1b, 0xe8, 0xca, 0x2b, 0xf0, 0x68, 0xbc, 0x02, 0x0f, 0x82, 0x1a, 0x3b, 0x28, 0xfc, 0xd9,
	0xfc, 0xdd, 0xdd, 0xf7, 0x7d, 0xd2, 0xcf, 0x6c, 0x52, 0x8a, 0x20, 0x6a, 0x52, 0x60, 0x9f, 0x15,
	0x58, 0x09, 0x1e, 0x5d, 0xab, 0x4b, 0xe4, 0xd6, 0x51, 0xa0, 0x6c, 0x9c, 0x64, 0x71, 0xa8, 0x88,
	0x54, 0x8d, 0xd0, 0x8d, 0xe5, 0xb2, 0x02, 0x6c, 0x6c, 0x58, 0xc5, 0xab, 0x62, 0x92, 0x96, 0xc2,
	0x6a, 0x10, 0xc6, 0x50, 0x10, 0x41, 0x93, 0xf1, 0x69, 0x3b, 0x57, 0x3a, 0x3c, 0x2d, 0x25, 0x2f,
	0xa9, 0x81, 0x7a, 0x55, 0x85, 0x98, 0x51, 0xce, 0x14, 0x9a, 0x59, 0x2b, 0x6a, 0xfd, 0x28, 0x02,
	0xc2, 0x9f, 0x47, 0x32, 0x9f, 0x0e, 0x8e, 0xfd, 0x8b, 0x50, 0x0a, 0x1d, 0x90, 0xed, 0xe2, 0xff,
	0xa9, 0xba, 0x18, 0x54, 0x69, 0x53, 0x91, 0xac, 0xe9, 0x95, 0x2c, 0x9a, 0x61, 0xa5, 0x22, 0xd7,
	0x7c, 0x47, 0xac, 0x45, 0xf4, 0x4e, 0x4f, 0xd8, 0xce, 0x1d, 0x3a, 0xaf, 0xc9, 0x2c, 0xd0, 0x5b,
	0x32, 0x1e, 0xb3, 0x9c, 0x8d, 0xdb, 0x38, 0xca, 0x47, 0x47, 0xa3, 0xe3, 0xed, 0x45, 0x2f, 0xcf,
	0x1e, 0xd8, 0xf8, 0x2a, 0x72, 0xcb, 0x6e, 0x19, 0xbb, 0xc1, 0x90, 0xac, 0xd9, 0x01, 0x8f, 0x2c,
	0x78, 0x0f, 0x8a, 0x5f, 0xaf, 0x41, 0x15, 0x39, 0xef, 0xc1, 0xfe, 0x2a, 0x99, 0xee, 0xbe, 0x7d,
	0x7c, 0xbe, 0x6f, 0xb0, 0x6c, 0x0b, 0x52, 0xf8, 0xe5, 0xfe, 0xfd, 0xde, 0xcf, 0x4f, 0x99, 0x5b,
	0x29, 0x37, 0xbb, 0xc0, 0xf3, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x74, 0x39, 0x67, 0xb0, 0xb0,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CatalogClient is the client API for Catalog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CatalogClient interface {
	GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type catalogClient struct {
	cc *grpc.ClientConn
}

func NewCatalogClient(cc *grpc.ClientConn) CatalogClient {
	return &catalogClient{cc}
}

func (c *catalogClient) GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/service.Catalog/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServer is the server API for Catalog service.
type CatalogServer interface {
	GetVersion(context.Context, *empty.Empty) (*VersionResponse, error)
}

func RegisterCatalogServer(s *grpc.Server, srv CatalogServer) {
	s.RegisterService(&_Catalog_serviceDesc, srv)
}

func _Catalog_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Catalog/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).GetVersion(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Catalog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Catalog",
	HandlerType: (*CatalogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _Catalog_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalog/pkg/pb/service.proto",
}
